name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

env:
  WRANGLER_ENV: ${{ github.actor }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    environment: development
    name: Deploy Downtown65 API
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Deploy API
        working-directory: apps/api
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          npx wrangler d1 migrations apply dt65-${{ env.WRANGLER_ENV }} -e ${{ env.WRANGLER_ENV }}
          npx wrangler deploy -e ${{ env.WRANGLER_ENV }}

#      - name: Deploy Cloudflare
#        uses: cloudflare/wrangler-action@v3
#        with:
#          workingDirectory: "apps/api"
#          environment: ${{ env.WRANGLER_ENV }}
#          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#          preCommands: |
#            wrangler d1 migrations apply dt65-${{ env.WRANGLER_ENV }} -e ${{ env.WRANGLER_ENV }}
#          command: versions upload
#          postCommands: |
#            wrangler d1 migrations apply dt65-${{ env.WRANGLER_ENV }} -
