name: Pull Request

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Concurrency group name ensures concurrent workflow runs wait for any in-progress job to finish
concurrency:
  group: merge-${{ github.ref }}

env:
  WRANGLER_ENV: ${{ github.actor }}

jobs:
  build:
    runs-on: ubuntu-22.04
    environment: development
    name: Setup
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Lint
        run: pnpm run lint:ci
      - name: Version check
        run:  pnpm run version-check
      - name: Typecheck
        run: pnpm run typecheck
      - name: Unit test
        run: pnpm run test

#      - name: Deploy API
#        working-directory: apps/api
#        env:
#          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
#          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
#        run: |
#          npx wrangler d1 migrations apply dt65-${{ env.WRANGLER_ENV }} -e ${{ env.WRANGLER_ENV }}
#          npx wrangler deploy -e ${{ env.WRANGLER_ENV }}
